# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Polygun < Formula
  desc "CLI"
  homepage "https://github.com/poly-gun/polygun-cli"
  version "0.1.14"
  license "MIT"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poly-gun/polygun-cli/releases/download/v0.1.14/polygun-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "615be2d7a0038f3f046e73122153c366a026f790725feab3865fb6dfb5ebb97e"

      def install
        bin.install "polygun-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poly-gun/polygun-cli/releases/download/v0.1.14/polygun-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9efd99ab2cc8bdb6adec4526e0e8445a7da905a601f2f071682d2b79da6431e8"

      def install
        bin.install "polygun-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/poly-gun/polygun-cli/releases/download/v0.1.14/polygun-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
        sha256 "c858547a838d26618900f35f03a550ecc24454a1dd0409664343b88d038c305d"

        def install
          bin.install "polygun-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/poly-gun/polygun-cli/releases/download/v0.1.14/polygun-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "d372f33677624fcb03da0c55da56c73e32a8105bb49f1ef05f7779a817de4630"

        def install
          bin.install "polygun-cli"
        end
      end
    end
  end
end
