# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolygunCli < Formula
  desc "CLI"
  homepage "https://github.com/poly-gun/polygun-cli"
  version "0.1.13"
  license "MIT"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poly-gun/polygun-cli/releases/download/v0.1.13/polygun-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "f099c4a4466c582cecb32dca3200d93ddfb03d2dbeaff7ef83f3638a3a3e89fd"

      def install
        bin.install "polygun-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poly-gun/polygun-cli/releases/download/v0.1.13/polygun-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "fedf22d1519120a34dfbb7dddd3c48c1319730903bf8e555609a1345e9aa867a"

      def install
        bin.install "polygun-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/poly-gun/polygun-cli/releases/download/v0.1.13/polygun-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
        sha256 "41cc071c1fe792b26ed996257f15740a0e6e00eda32df060a9ffdbda3d7d4ae9"

        def install
          bin.install "polygun-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/poly-gun/polygun-cli/releases/download/v0.1.13/polygun-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "4a9b5cd9740521456bc2537e1adcc2bf1ad40e12b63a43c48f167a06193d8246"

        def install
          bin.install "polygun-cli"
        end
      end
    end
  end

  conflicts_with "polygun-cli"
end
